name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read

jobs:
<<<<<<< HEAD
  deploy:
=======
  golangci:
>>>>>>> f6cdfae (Added github actions)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Dependencies
        run: sudo apt install -y devscripts debhelper build-essential dh-python python3-all

      - name: Build
        run: debuild -b -us -uc

      - name: Archive debian packages
        uses: actions/upload-artifact@v3
        with:
          name: debian-packages
          path: |
            /workspace/bad-apples*.deb
